[[main]]
  name = "Concepts"
  url = "/"
  weight = 10

[[main]]
  name = "How To"
  url = "/docs/how-tos/basics/install-lotus/"
  weight = 20

[[main]]
  name = "Examples"
  url = "/docs/examples/basics/hello-world/"
  weight = 30

[[main]]
  name = "Reference"
  url = "/docs/reference/lotus-api/"
  weight = 40



[[concepts]]
  name = "Basics"
  weight = 10
  identifier = "concepts-basics"
  url = "/docs/concepts/basics/"

[[concepts]]
  name = "Gas"
  weight = 20
  identifier = "concepts-gas"
  url = "/docs/concepts/gas/"

[[concepts]]
  name = "Messages"
  weight = 30
  identifier = "concepts-messages"
  url = "/docs/concepts/implementations/"

[[concepts]]
  name = "Actors"
  weight = 40
  identifier = "concepts-actors"
  url = "/docs/concepts/actors/"

[[concepts]]
  name = "EVM"
  weight = 50
  identifier = "concepts-evm"
  url = "/docs/concepts/evm/"

[[concepts]]
  name = "Implementations"
  weight = 60
  identifier = "concepts-implementations"
  url = "/docs/concepts/implementations/"



[[howto]]
  name = "Basics"
  weight = 5 
  identifier = "how-to-basics"
  url = "/docs/how-to/actors/"

[[howto]]
  name = "Actors"
  weight = 10
  identifier = "how-to-actors"
  url = "/docs/how-to/actors/"

[[howto]]
  name = "WASM"
  weight = 20
  identifier = "how-to-wasm"
  url = "/docs/how-to/wasm/"



[[examples]]
  name = "Basics"
  weight = 10
  identifier = "examples-basics"
  url = "/docs/examples/basics/"

[[examples]]
  name = "Actors"
  weight = 20
  identifier = "examples-actors"
  url = "/docs/examples/actors/"

[[examples]]
  name = "Ethereum"
  weight = 30
  identifier = "examples-ethereum"
  url = "/docs/examples/ethereum/"



[[reference]]
  name = "Lotus"
  weight = 10
  identifier = "reference-lotus"
  url = "/docs/reference/lotus/"



[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/filecoin-project/fvm"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/lotus_web3"
  weight = 20



# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10

